name: Test app

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3.6.0
        with:
          node-version-file: ./.node-version
          cache: npm
          cache-dependency-path: ./package-lock.json
      - run: npm ci
      - run: npm run build
      - run: npm run lint
